sudo: required
language: generic

services:
   - docker
before_install:
   - docker build -t 187600/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true 187600/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-west-1"
   app: "docker"
   env: "Docker-env"
   bucket_name: "arn:aws:s3:::elasticbeanstalk-us-west-1-218135838242"
   bucket_path: "docker"
   on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key: $AWS_SECRET_KEY