sudo: required
language: generic

services:
   - docker
before_install:
   - docker build -t 187600/docker-react dockerfile .

script:
   - docker run -e CI=true 187600/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-west-1"
   app: "docker"
   env: "Docker-env-1"
   bucket_name: "elasticbeanstalk-us-west-1-218135838242"
   bucket_path: "s3://elasticbeanstalk-us-west-1-218135838242/resources/_runtime/_embedded_extensions/docker"
   on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key: $AWS_SECRET_KEY