sudo: required
services:
   - docker
before_install:
   - docker build -t 187600/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true 187600/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "ap-south-1"
   app: "docker"
   env: "Docker-env"
   bucket_name: "elasticbeanstalk-ap-south-1-218135838242"
   bucket_path: "docker"
   on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
      secure: "$AWS_SECRET_KEY"
